### ISSUE TITLE
Predefined value for textfield

### ISSUE THREAD

**Issue by rostaingc** [joseestrella89/react-native-dialog-input#14]
Hi,
I was wondering if you could add the possibility to set a default value for the textfield.
I would like to use it as an edit button: User clicks on a label and it pops up the dialog input with the current value already inputted.
Thanks

**Comment by joseestrella89** [comment]
Of course, Added in [1.0.7](https://github.com/joseestrella89/react-native-dialog-input/commit/5888006b81a3bf7110bf3cf2e5eb5fb4e5714fea)
