### ISSUE TITLE
Great library. Just one little comment

### ISSUE THREAD

**Issue by ansonyao** [joseestrella89/react-native-dialog-input#19]
Thanks for the great library. Enjoy it a lot. Just one minor thing, in the example, 

title={"DialogInput 1"}

can be simply as:

title="DialogInput 1"

**Comment by gonzalovinas** [comment]
Is this better in some other way than eye clear syntax ? Asking if I am missing something ... nothing else.. thanks

**Comment by ansonyao** [comment]
Just eye clearing. haha
