### ISSUE TITLE
When dialog is closed inputModal value is not set to empty

### ISSUE THREAD

**Issue by penmatsa** [joseestrella89/react-native-dialog-input#2]
When text is entered in TextInput and submit button is clicked after that if I open the dialog again and press the submit button without entering text in TextInput it returns the old value.

**Comment by ithustle** [comment]
Hi @penmatsa I commited this issue on https://github.com/ithustle/react-native-dialog-input/commit/7cf5ff9d7ddd6b0f7af5b59774f7336f272caa8b

**Comment by franck-nadeau** [comment]
I had the same problem, so I fixed it and created a PR for it. 

https://github.com/joseestrella89/react-native-dialog-input/pull/12

**Comment by joseestrella89** [comment]
Sorry for the delay. Added in version [1.0.6](https://github.com/joseestrella89/react-native-dialog-input/commit/a921ad9c9942dbff2e184e5243913e9b49ae700e)

**Comment by franck-nadeau** [comment]
The bug is still present in 1.0.6. 

**To reproduce**

1. Enter text and hit submit or cancel.
2. Re-open the dialog and hit submit without changing the text.
3. the submitInput is called with the text previously interred.

**Comment by franck-nadeau** [comment]
I updated my code on my PR, since it had a conflict.
