### ISSUE TITLE
maxlength prop doesn't actually work

### ISSUE THREAD

**Issue by arjun-bhatt** [joseestrella89/react-native-dialog-input#36]
Peeked through the source code too and doesn't look like it's accounted for

**Comment by joseestrella89** [comment]
Hi @arjun-bhatt it is added from this [commit](https://github.com/joseestrella89/react-native-dialog-input/commit/e21788885c4605394cba44f3a8154a812c91c96d) and it should comes from the `textInputProps` [prop](https://github.com/joseestrella89/react-native-dialog-input#properties)

react-native-dialog-input@1.0.8

```
<DialogInput isDialogVisible={this.state.showDialog}
      title={"DialogInput 1"}
      message={"Message for DialogInput #1"}
      hintInput ={"HINT INPUT"}
      submitInput={ (inputText) => {this.sendInput(inputText)} }
      textInputProps={{
        maxLength: 5,
      }}
      closeDialog={ () => {this.showDialog(false)}}>
</DialogInput>
```
