### ISSUE TITLE
There should be an option for dismissing the dialog when clicking outside of it

### ISSUE THREAD

**Issue by firefueled** [joseestrella89/react-native-dialog-input#7]
Something like `cancelable` or `dismissable` should control whether a click outside of the bounding boxes dismisses the dialog in the ame way tha a click on 'Cancel' would.

**Comment by ithustle** [comment]
Hi @firefueled I commited this issue on https://github.com/ithustle/react-native-dialog-input/commit/7cf5ff9d7ddd6b0f7af5b59774f7336f272caa8b

**Comment by joseestrella89** [comment]
Sorry for the delay. Merged in [1.0.6](https://github.com/joseestrella89/react-native-dialog-input/commit/a921ad9c9942dbff2e184e5243913e9b49ae700e)

**Comment by elmcapp** [comment]
We need the option to choose if we want to Dismissing the dialog when clicking outside.
Is there a prop for this or can you add this Dismissing={true or false}
