### ISSUE TITLE
Text Input not working

### ISSUE THREAD

**Issue by steinitz** [joseestrella89/react-native-dialog-input#9]
Hi,

When I type I don't see any characters - maybe a little flicker.  My function that receives the text input from the dialog only gets the last character I've typed.

I hope this report is useful.

**Comment by ithustle** [comment]
Hi @SteveSteinitz I commited this issue on https://github.com/ithustle/react-native-dialog-input/commit/7cf5ff9d7ddd6b0f7af5b59774f7336f272caa8b

**Comment by SahanDll** [comment]
Is this fix available in 1.0.5?

**Comment by steinitz** [comment]
Thanks @ithustle - I hacked the other one to work.  Your fix is nice.  I gave your project it's first star :)

**Comment by ithustle** [comment]
@SahanDll, noup.

**Comment by stephendiadamo** [comment]
@SteveSteinitz How did you hack it to work? I'm having the same problem where my text gets erased as I type it.

**Comment by steinitz** [comment]
Well @stephendiadamo, it's a dumb hack and might not work for you.  I removed line 46:

`value={this.state.inputModal}`

I think I removed another line to prevent a resulting eslint warning.

I would recommend, instead, using @ithustle 's more-sound fix.

**Comment by cyb3rsalih** [comment]
problem is still there. How to correct this?

**Comment by SahanDll** [comment]
No option, I have created my own dialog box using Model :)

**Comment by andryuha49** [comment]
Hi @joseestrella89.
Please update package on npmjs.com. After the last commit, the problem was fixed but the package still not working on npmjs.com.

**Comment by joseestrella89** [comment]
Sorry for the delay. Added in merge [1.0.6](https://github.com/joseestrella89/react-native-dialog-input/commit/a921ad9c9942dbff2e184e5243913e9b49ae700e)
